# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: 홈
    url: /#top
    weight: 10
  - name: 스케쥴
    url: /#schedule
    weight: 20
  - name: 연사
    url: /#speakers
    weight: 30
    weight: 30
  - name: 티켓
    weight: 40
    hasChildren: true
  - parent: 티켓
    name: BTC
    url: https://store.btcmap.kr/meetup/Bitcoin_Mini_Conference/11/
  - parent: 티켓
    name: KRW
    url: https://smartstore.naver.com/promenadecastle/products/12055415750
