# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: event
    local_business_type: 'Conference'
    org_name: 'Bitcoin Mini Conference'
    description: 'Bitcoin Mini Conference. Seoul. Novemeber 29-30'
    twitter: 'https://x.com/bitcoinminiconf'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      # Logo filename in `assets/media/` folder
      filename: "logo.svg"
    #button:
    #  enable: true
    #  text: "Get Tickets"
    #  url: /#speakers
    show_search: false
    show_theme_chooser: true

## Site footer
#footer:
#  copyright:
#    notice: '© {year} My Company'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
